[project]
name = "lounge-lizard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "openai>=1.85.0",
    "playwright>=1.52.0",
    "sv-ttk>=2.6.1",
    "ttkbootstrap>=1.13.10",
]
